### PR TITLE
Created simplecalculator.py

### PR DESCRIPTION
**Pull request by Naveen343**
Made a Simple calculator in python with description to know the use of working of each part of code.

### CODE REVIEW

**Comment by Princekumaraj** [comment]
Give star and follow master

**Comment by Naveen343** [comment]
What do you mean by follow master...follow you?

**Comment by Princekumaraj** [comment]
Yes bro .

**Comment by Naveen343** [comment]
Ok bro...

**Comment by Princekumaraj** [comment]
Thanks bro ... Keep supporting

**Pull request merged**
